version: "3.3"
services:
    mongodb:
        image: mongo:5.0
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=zz3f3
            - MONGO_INITDB_ROOT_PASSWORD=easyma
#    mongo-gui:
#        container_name: "mongo-gui"
#        image: ugleiton/mongo-gui
#        ports:
#            - "4321:4321"
#        environment:
#            - MONGO_URL=mongodb://zz3f3:easyma@mongodb
    php:
        container_name: "php"
        image: citizen63000/ubuntu-php-mongo:1.1
        depends_on:
            -   mongodb
        ports:
           - 8080:80
        volumes:
           - ./www:/var/www/app/
    redis:
        container_name: redis
        image: redis:7.0.5
        ports:
            - 6379:6379
    redis-commander:
        container_name: redis-commander
        image: rediscommander/redis-commander:latest
        depends_on:
            -   redis
        ports:
            - 8081:8081
        environment:
            - REDIS_HOSTS=local:redis:6379
    influxdb:
        image: influxdb:1.8
        ports:
            - "8086:8086"
        environment:
            - INFLUXDB_DB=k6
    grafana:
        image: grafana/grafana:latest
        depends_on:
            -   influxdb
        ports:
            - "3000:3000"
        environment:
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_BASIC_ENABLED=false
        volumes:
            - ./grafana/dashboards:/var/lib/grafana/dashboards
            - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
            - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    k6:
        image: loadimpact/k6:latest
        depends_on:
            - php
            - influxdb
#        entrypoint: /bin/sh
#        user: root
        ports:
            - "6565:6565"
        environment:
            - K6_OUT=influxdb=http://influxdb:8086/k6
        volumes:
            - ./k6:/scripts
